#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xf86-input-mouse
Version  : 1.9.2
Release  : 17
URL      : http://xorg.freedesktop.org/releases/individual/driver/xf86-input-mouse-1.9.2.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/driver/xf86-input-mouse-1.9.2.tar.gz
Summary  : X.Org mouse input driver for non-evdev OS'es
Group    : Development/Tools
License  : HPND
Requires: xf86-input-mouse-lib
Requires: xf86-input-mouse-doc
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xorg-server)

%description
Mouse Support in xf86-input-mouse
Original version written by Kazutaka Yokota for XFree86 on 17 December 2002
Updated by Alan Coopersmith for X.Org releases
____________________________________________________________

%package dev
Summary: dev components for the xf86-input-mouse package.
Group: Development
Requires: xf86-input-mouse-lib
Provides: xf86-input-mouse-devel

%description dev
dev components for the xf86-input-mouse package.


%package doc
Summary: doc components for the xf86-input-mouse package.
Group: Documentation

%description doc
doc components for the xf86-input-mouse package.


%package lib
Summary: lib components for the xf86-input-mouse package.
Group: Libraries

%description lib
lib components for the xf86-input-mouse package.


%prep
%setup -q -n xf86-input-mouse-1.9.2

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/xorg/xf86-mouse-properties.h
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man4/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/xorg/modules/input/mouse_drv.so
